/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author emilianaplaz
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz2
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    //ESTE METODO DEVUELVE TRUE SI SE PUEDE AUMENTAR Y DEVUELVE FALSE SI NO SE PUEDE. Solo funciona para apple
    public boolean permisoDeAumentoDeTrabajadorApple(){
        boolean respuesta = false;
        int totalTrabajadores = Global.getApple().cantidadTrabajadores(); 
        if(totalTrabajadores < 18){  //CARNET DE Stefano TERMINA EN 6 POR LO TANTO -> 12+6=18
            respuesta = true;
        }
        return respuesta;
    }
    
    //ESTE METODO DEVUELVE TRUE SI SE PUEDE AUMENTAR Y DEVUELVE FALSE SI NO SE PUEDE. Solo funciona para cartoon HP
    public boolean permisoDeAumentoDeTrabajadorHP(){
        boolean respuesta = false;
        int totalTrabajadores = Global.getHP().cantidadTrabajadores();
        if(totalTrabajadores < 15){ //CARNET DE Emiliana TERMINA EN 3 POR LO TANTO -> 12+3=15
            respuesta = true;
        }
        return respuesta;
    }
    
    public boolean permisoDeAumentoDeTrabajadorAppleEnDatosIniciales(){
        boolean respuesta = false;
        int totalTrabajadores = Integer.parseInt(prodplacabaseApple.getText())+
                                Integer.parseInt(prodcpuApple.getText())+
                                Integer.parseInt(prodramApple.getText())+
                                Integer.parseInt(prodfuenteApple.getText())+
                                Integer.parseInt(prodgraficaApple.getText())+
                                Integer.parseInt(ensambladoresApple.getText()); 
        if(totalTrabajadores < 18){  //Carnet Stefano
            respuesta = true;
        }
        return respuesta;
    }
    
    public boolean permisoDeAumentoDeTrabajadorHPEnDatosIniciales(){
        boolean respuesta = false;
        int totalTrabajadores = Integer.parseInt(prodplacabaseHP.getText())+
                                Integer.parseInt(prodcpuHP.getText())+
                                Integer.parseInt(prodramHP.getText())+
                                Integer.parseInt(prodfuenteHP.getText())+
                                Integer.parseInt(prodgraficaHP.getText())+
                                Integer.parseInt(ensambladoresHP.getText()); 
        if(totalTrabajadores < 15){  //Carnet Emiliana
            respuesta = true;
        }
        return respuesta;
    }
    
    public void cambiarPasoDeDias(int t){
        diasInicio.setText(Integer.toString(t));
        diasDisney.setText(Integer.toString(t));
        diasCN.setText(Integer.toString(t));
    }
    
    public void cambiarDiasLanzamiento(int t,int tipoCompania){
        if(tipoCompania == 0){
            diasEntregaDisney.setText(Integer.toString(t));
        }else{
            diasEntregaCartoonNetwork.setText(Integer.toString(t));
        }
    }
    
    public void cambiarPMActividad(String t,int tipoCompania){
        if(tipoCompania == 0){
            pmActividadDisney.setText(t);
        }else{
            pmCNActividadd.setText(t);
        }
    }
    
    public void cambiarFaltasPM(int t,int tipoCompania){
        if(tipoCompania == 0){
            faltasPMDisney.setText(Integer.toString(t));
        }else{
            faltasPMCN.setText(Integer.toString(t));
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        diasInicio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        utilidadesappleinicio = new javax.swing.JLabel();
        operativosappleinicio = new javax.swing.JLabel();
        gananciasappleinicio = new javax.swing.JLabel();
        estandarappleinicio = new javax.swing.JLabel();
        graficasappleinicio = new javax.swing.JLabel();
        utilidadeshpinicio = new javax.swing.JLabel();
        operativoshpinicio = new javax.swing.JLabel();
        gananciashpbruto = new javax.swing.JLabel();
        estandarhpinicio = new javax.swing.JLabel();
        graficashpinicio = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        prodplacabaseApple = new javax.swing.JLabel();
        prodcpuApple = new javax.swing.JLabel();
        prodramApple = new javax.swing.JLabel();
        prodfuenteApple = new javax.swing.JLabel();
        prodgraficaApple = new javax.swing.JLabel();
        ensambladoresApple = new javax.swing.JLabel();
        prodplacabaseHP = new javax.swing.JLabel();
        prodcpuHP = new javax.swing.JLabel();
        prodramHP = new javax.swing.JLabel();
        prodfuenteHP = new javax.swing.JLabel();
        prodgraficaHP = new javax.swing.JLabel();
        ensambladoresHP = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Apple vs HP");

        jLabel2.setText("DIAS:");

        diasInicio.setText("0");

        jLabel4.setText("Apple");

        jLabel5.setText("HP");

        jLabel6.setText("Utilidades");

        jLabel7.setText("Costos Operativos");

        jLabel8.setText("Ganancias en bruto");

        jLabel9.setText("Computadoras Entándar");

        jLabel10.setText("Computadoras Gráficas");

        utilidadesappleinicio.setText("0");

        operativosappleinicio.setText("0");

        gananciasappleinicio.setText("0");

        estandarappleinicio.setText("0");

        graficasappleinicio.setText("0");

        utilidadeshpinicio.setText("0");

        operativoshpinicio.setText("0");

        gananciashpbruto.setText("0");

        estandarhpinicio.setText("0");

        graficashpinicio.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diasInicio))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(utilidadesappleinicio)
                            .addComponent(operativosappleinicio)
                            .addComponent(gananciasappleinicio)
                            .addComponent(estandarappleinicio)
                            .addComponent(graficasappleinicio)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(utilidadeshpinicio)
                    .addComponent(jLabel5)
                    .addComponent(operativoshpinicio)
                    .addComponent(gananciashpbruto)
                    .addComponent(estandarhpinicio)
                    .addComponent(graficashpinicio))
                .addGap(74, 74, 74))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(utilidadesappleinicio)
                        .addComponent(utilidadeshpinicio))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(diasInicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(operativosappleinicio)
                    .addComponent(operativoshpinicio))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(gananciasappleinicio)
                    .addComponent(gananciashpbruto))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(estandarappleinicio)
                    .addComponent(estandarhpinicio))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(graficasappleinicio)
                    .addComponent(graficashpinicio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Home", jPanel2);

        jPanel3.setLayout(null);

        jLabel11.setText("Configuración Inicial");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(290, 16, 116, 17);

        jLabel12.setText("Productors placa base");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(32, 152, 132, 17);

        jLabel13.setText("Productores CPU");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(30, 190, 100, 17);

        jLabel14.setText("Productores RAM");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(32, 222, 102, 17);

        jLabel15.setText("Productores fuentes de energía");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(32, 257, 182, 17);

        jLabel16.setText("Productores tarjeta gráfica");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(32, 292, 153, 17);

        jLabel17.setText("Ensambladores");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(32, 327, 91, 17);

        jLabel18.setText("Apple");
        jPanel3.add(jLabel18);
        jLabel18.setBounds(350, 90, 34, 17);

        jLabel19.setText("HP");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(503, 89, 17, 17);

        prodplacabaseApple.setText("0");
        jPanel3.add(prodplacabaseApple);
        prodplacabaseApple.setBounds(358, 152, 7, 17);

        prodcpuApple.setText("0");
        jPanel3.add(prodcpuApple);
        prodcpuApple.setBounds(360, 190, 7, 17);

        prodramApple.setText("0");
        jPanel3.add(prodramApple);
        prodramApple.setBounds(358, 222, 7, 17);

        prodfuenteApple.setText("0");
        jPanel3.add(prodfuenteApple);
        prodfuenteApple.setBounds(358, 257, 7, 17);

        prodgraficaApple.setText("0");
        jPanel3.add(prodgraficaApple);
        prodgraficaApple.setBounds(358, 292, 7, 17);

        ensambladoresApple.setText("0");
        jPanel3.add(ensambladoresApple);
        ensambladoresApple.setBounds(358, 327, 7, 17);

        prodplacabaseHP.setText("0");
        jPanel3.add(prodplacabaseHP);
        prodplacabaseHP.setBounds(510, 150, 16, 17);

        prodcpuHP.setText("0");
        jPanel3.add(prodcpuHP);
        prodcpuHP.setBounds(510, 190, 49, 17);

        prodramHP.setText("0");
        jPanel3.add(prodramHP);
        prodramHP.setBounds(510, 220, 7, 17);

        prodfuenteHP.setText("0");
        jPanel3.add(prodfuenteHP);
        prodfuenteHP.setBounds(510, 260, 7, 17);

        prodgraficaHP.setText("0");
        jPanel3.add(prodgraficaHP);
        prodgraficaHP.setBounds(510, 290, 7, 17);

        ensambladoresHP.setText("0");
        jPanel3.add(ensambladoresHP);
        ensambladoresHP.setBounds(510, 320, 7, 17);

        jButton1.setText("+");
        jPanel3.add(jButton1);
        jButton1.setBounds(380, 320, 30, 23);

        jButton2.setText("+");
        jPanel3.add(jButton2);
        jButton2.setBounds(540, 320, 30, 23);

        jButton3.setText("+");
        jPanel3.add(jButton3);
        jButton3.setBounds(380, 190, 30, 23);

        jButton4.setText("+");
        jPanel3.add(jButton4);
        jButton4.setBounds(380, 220, 30, 23);

        jButton5.setText("+");
        jPanel3.add(jButton5);
        jButton5.setBounds(380, 260, 30, 23);

        jButton6.setText("+");
        jPanel3.add(jButton6);
        jButton6.setBounds(380, 290, 30, 23);

        jButton7.setText("+");
        jPanel3.add(jButton7);
        jButton7.setBounds(380, 150, 30, 23);

        jButton8.setText("+");
        jPanel3.add(jButton8);
        jButton8.setBounds(540, 150, 30, 23);

        jButton9.setText("+");
        jPanel3.add(jButton9);
        jButton9.setBounds(540, 150, 30, 23);

        jButton10.setText("+");
        jPanel3.add(jButton10);
        jButton10.setBounds(540, 190, 30, 23);

        jButton11.setText("+");
        jPanel3.add(jButton11);
        jButton11.setBounds(540, 220, 30, 23);

        jButton12.setText("+");
        jPanel3.add(jButton12);
        jButton12.setBounds(540, 260, 30, 23);

        jButton13.setText("+");
        jPanel3.add(jButton13);
        jButton13.setBounds(540, 290, 30, 23);

        jTabbedPane2.addTab("Config", jPanel3);

        jPanel4.setLayout(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel1);
        jPanel1.setBounds(615, 250, 100, 100);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel6.setLayout(null);

        jLabel20.setText("Trabajadores Activos");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(70, 10, 123, 17);

        jLabel21.setText("Productores placa base");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(20, 40, 150, 17);

        jLabel22.setText("Productores CPU");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(20, 70, 100, 17);

        jLabel23.setText("Productores RAM");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(20, 100, 102, 17);

        jLabel24.setText("Productores fuentes de energia");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(20, 130, 182, 17);

        jLabel25.setText("Productores tarjeta gráfica");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(20, 160, 153, 17);

        jLabel26.setText("Ensambladores");
        jPanel6.add(jLabel26);
        jLabel26.setBounds(20, 190, 91, 17);

        jPanel4.add(jPanel6);
        jPanel6.setBounds(30, 30, 310, 220);

        jTabbedPane2.addTab("Apple", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("HP", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel diasInicio;
    private javax.swing.JLabel ensambladoresApple;
    private javax.swing.JLabel ensambladoresHP;
    private javax.swing.JLabel estandarappleinicio;
    private javax.swing.JLabel estandarhpinicio;
    private javax.swing.JLabel gananciasappleinicio;
    private javax.swing.JLabel gananciashpbruto;
    private javax.swing.JLabel graficasappleinicio;
    private javax.swing.JLabel graficashpinicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel operativosappleinicio;
    private javax.swing.JLabel operativoshpinicio;
    private javax.swing.JLabel prodcpuApple;
    private javax.swing.JLabel prodcpuHP;
    private javax.swing.JLabel prodfuenteApple;
    private javax.swing.JLabel prodfuenteHP;
    private javax.swing.JLabel prodgraficaApple;
    private javax.swing.JLabel prodgraficaHP;
    private javax.swing.JLabel prodplacabaseApple;
    private javax.swing.JLabel prodplacabaseHP;
    private javax.swing.JLabel prodramApple;
    private javax.swing.JLabel prodramHP;
    private javax.swing.JLabel utilidadesappleinicio;
    private javax.swing.JLabel utilidadeshpinicio;
    // End of variables declaration//GEN-END:variables
}
